### ISSUE TITLE
rewrite docs suggestion

### ISSUE THREAD

**Issue by jacobdalamb** [lycheeverse/lycheeverse.github.io#63]
I think a docs rewrite using [starlight](https://starlight.astro.build/) would be great enhancement for the site.

**Comment by mre** [comment]
Why exactly? What are the problems with the current site?

**Comment by jacobdalamb** [comment]
> Why exactly? What are the problems with the current site?

It could benefit from better [performance](https://pagespeed.web.dev/analysis/https-lychee-cli-rs/el6dco4fx6?form_factor=desktop), improved SEO, can maintain the existing design with a more streamlined look and has a excellent developer experience.

**Comment by mre** [comment]
I agree that performance is not so great and since everything is rendered client-side, SEO could also be better.
However, my hope was to find an engine that works without any JavaScript and renders beautiful HTML from Markdown in the design we have now.
I tried a few options like mdbook or docusaurus, but none of them were great.

I just checked a few examples from the [Starlight Showcase](https://starlight.astro.build/resources/showcase/), and it looks like they work without JavaScript, which is great.
If we can replicate the same design, I'd be willing to give it a shot, but I'm a bit afraid that it would be a lot of work.
Would you be willing to do the rewrite?

**Comment by jacobdalamb** [comment]
> I agree that performance is not so great and since everything is rendered client-side, SEO could also be better. However, my hope was to find an engine that works without any JavaScript and renders beautiful HTML from Markdown in the design we have now. I tried a few options like mdbook or docusaurus, but none of them were great.
> 
> I just checked a few examples from the [Starlight Showcase](https://starlight.astro.build/resources/showcase/), and it looks like they work without JavaScript, which is great. If we can replicate the same design, I'd be willing to give it a shot, but I'm a bit afraid that it would be a lot of work. Would you be willing to do the rewrite?

[Starlight](https://starlight.astro.build/) is really great at keeping Javascript in the sever-side unless you want client-side interactivity. I am willing to do the rewrite with minimal changes to the current design.

**Comment by mre** [comment]
Sounds good. Thanks for that. ☺️
