### ISSUE TITLE
Document the functionality per scheme

### ISSUE THREAD

**Issue by sanmai-NL** [lycheeverse/lycheeverse.github.io#7]
To determine what to `include` or `exclude`, the user needs to know which schemes can be checked. Only indirectly, there's a reference to `http`, `https` and `mailto`.

**Comment by mre** [comment]
Interesting. I never thought about that because any scheme is supported here. At least when passing it as `--scheme foo`, it would technically work. That's because we only check if the URI [starts with the given scheme](https://github.com/lycheeverse/lychee/blob/1cdc5bf49990940371ae1722fc992d6c64c4c0e9/lychee-lib/src/filter/mod.rs#L150-L155):

```rust
    pub fn is_scheme_excluded(&self, uri: &Uri) -> bool {
        if self.schemes.is_empty() {
            return false;
        }
        !self.schemes.contains(uri.scheme())
    }
``` 

Of course, in practice not every scheme can be checked.
It must be parseable as a URL by the [url](https://docs.rs/url/latest/url/) crate and by [reqwest](https://github.com/seanmonstar/reqwest).

reqwest only supports http and https right now:
https://github.com/seanmonstar/reqwest/blob/17c893ffc0d3832d61cb1c0cf278340b7e95557e/src/async_impl/client.rs#L1764-L1766

We support file and mailto on top of that.
I will mention that in the documentation and link it here. Thanks for the tip.

**Comment by mre** [comment]
I've added some documentation now:
https://github.com/lycheeverse/lycheeverse.github.io/commit/5787374a02b642ffabb861a4ed9dfb472ede3cc8

**Comment by mre** [comment]
Already live: https://lychee.cli.rs/#/usage/cli?id=on-schemes

**Comment by mre** [comment]
I went ahead and added it to the main [lychee](https://github.com/lycheeverse/lychee) README, too.
